version: '3.8'

services:
  mysql-service:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    deploy:
      replicas: 3

  ngnix-service:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"

